[package]
name = "printertui"
version = "0.2.0"
license = "MIT"
edition = "2024"

[dependencies]
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg"] }
lopdf = { version = "0.45.0", default-features = false }
minreq = "3.0.0"
pdf-writer = "0.15.0"
ratatui = "0.30.2"
unicode-width = "0.2.2"

[target."cfg(windows)".dependencies]
mdns-sd = "0.21.4"
pdfium-render = { version = "0.9.4", default-features = false, features = ["pdfium_7881", "thread_safe"] }
rfd = "0.17.2"
windows = { version = "0.62", features = ["Win32_Graphics_Printing", "Win32_Graphics_Gdi", "Win32_Foundation", "Win32_Storage_Xps", "Win32_System_Threading", "Devices_Scanners", "Devices_Enumeration", "Storage", "Storage_Streams", "Foundation", "Foundation_Collections", "Media_Ocr", "Graphics_Imaging", "Globalization", "Win32_System_SystemInformation", "Win32_Security", "Security_Cryptography", "Storage_Search", "Win32_Devices_DeviceAndDriverInstallation", "Win32_Devices_Properties"] }

[build-dependencies]
embed-resource = "3.0.11"
sha2 = "0.11.0"
